### ISSUE TITLE
qmcalc needs documentation

### ISSUE THREAD

**Issue by jwalden** [dspinellis/cqmetrics#19]
The README file doesn't provide sufficient documentation to use qmcalc, either in the form of an expanded README or a man page. For example, the meaning of empty strings as NA isn't documented anywhere. I'm willing to help write documentation, but I don't know everything about qmcalc.

**Comment by dspinellis** [comment]
Thank you for the comment! The README file links [here](https://github.com/dspinellis/cqmetrics/blob/master/metrics.md) for expanded information, which also (since yesterday) documents the NA values. A *man* page (`qmcalc.1`) is generated automatically when building the program. Documentation can always be improved, so I'd welcome a pull request documenting things you struggled with.
